package com.util.SQLGenerator;

public class SQLConstant {
	
	public static String CREATE_QUERY="CREATE TABLE <TABLENAME> (<COLUMNSDATA>) TABLESPACE GLX_DATA";
	
	public static String COMMENT_QUERY="COMMENT ON COLUMN <TABLENAME>.\"<COLUMN_NAME>\" IS '<COLUMN_TEXT>'";
	
	public static String INDEX_QUERY="CREATE INDEX <INDEX_NAME> ON <TABLENAME> (<COLUMN_NAME>) ORDER BY <COLUMN_NAME> ASC";
	
	public static String UNIQUE_INDEX_QUERY="CREATE UNIQUE INDEX <INDEX_NAME> ON <TABLENAME> (<COLUMN_NAME>) ORDER BY <COLUMN_NAME> ASC";
	
	
}
