//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.25 at 03:42:37 PM EDT 
//


package com.staples.jaxb.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Details">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Detail">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Error">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Item">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="SKU" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="PurchaseOrderNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="UPCCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="TransactionNmb" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Amount" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Header">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ApplicationAdviceHeader">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ReferenceDate" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="ReferenceNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="TransactionType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="VendorNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "details",
    "header"
})
@XmlRootElement(name = "ApplicationAdvice")
public class ApplicationAdvice {

    @XmlElement(name = "Details", required = true)
    protected ApplicationAdvice.Details details;
    @XmlElement(name = "Header", required = true)
    protected ApplicationAdvice.Header header;

    /**
     * Gets the value of the details property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationAdvice.Details }
     *     
     */
    public ApplicationAdvice.Details getDetails() {
        return details;
    }

    /**
     * Sets the value of the details property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationAdvice.Details }
     *     
     */
    public void setDetails(ApplicationAdvice.Details value) {
        this.details = value;
    }

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationAdvice.Header }
     *     
     */
    public ApplicationAdvice.Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationAdvice.Header }
     *     
     */
    public void setHeader(ApplicationAdvice.Header value) {
        this.header = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Detail">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Error">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Item">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="SKU" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="PurchaseOrderNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="UPCCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="TransactionNmb" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Amount" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "detail"
    })
    public static class Details {

        @XmlElement(name = "Detail", required = true)
        protected ApplicationAdvice.Details.Detail detail;

        /**
         * Gets the value of the detail property.
         * 
         * @return
         *     possible object is
         *     {@link ApplicationAdvice.Details.Detail }
         *     
         */
        public ApplicationAdvice.Details.Detail getDetail() {
            return detail;
        }

        /**
         * Sets the value of the detail property.
         * 
         * @param value
         *     allowed object is
         *     {@link ApplicationAdvice.Details.Detail }
         *     
         */
        public void setDetail(ApplicationAdvice.Details.Detail value) {
            this.detail = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Error">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Item">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="SKU" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="PurchaseOrderNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="UPCCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="TransactionNmb" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Amount" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "error",
            "transactionNmb",
            "amount",
            "date"
        })
        public static class Detail {

            @XmlElement(name = "Error", required = true)
            protected ApplicationAdvice.Details.Detail.Error error;
            @XmlElement(name = "TransactionNmb", required = true)
            protected String transactionNmb;
            @XmlElement(name = "Amount")
            protected float amount;
            @XmlElement(name = "Date")
            protected int date;

            /**
             * Gets the value of the error property.
             * 
             * @return
             *     possible object is
             *     {@link ApplicationAdvice.Details.Detail.Error }
             *     
             */
            public ApplicationAdvice.Details.Detail.Error getError() {
                return error;
            }

            /**
             * Sets the value of the error property.
             * 
             * @param value
             *     allowed object is
             *     {@link ApplicationAdvice.Details.Detail.Error }
             *     
             */
            public void setError(ApplicationAdvice.Details.Detail.Error value) {
                this.error = value;
            }

            /**
             * Gets the value of the transactionNmb property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTransactionNmb() {
                return transactionNmb;
            }

            /**
             * Sets the value of the transactionNmb property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTransactionNmb(String value) {
                this.transactionNmb = value;
            }

            /**
             * Gets the value of the amount property.
             * 
             */
            public float getAmount() {
                return amount;
            }

            /**
             * Sets the value of the amount property.
             * 
             */
            public void setAmount(float value) {
                this.amount = value;
            }

            /**
             * Gets the value of the date property.
             * 
             */
            public int getDate() {
                return date;
            }

            /**
             * Sets the value of the date property.
             * 
             */
            public void setDate(int value) {
                this.date = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Item">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="SKU" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="PurchaseOrderNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="UPCCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "item",
                "description",
                "code"
            })
            public static class Error {

                @XmlElement(name = "Item", required = true)
                protected ApplicationAdvice.Details.Detail.Error.Item item;
                @XmlElement(name = "Description", required = true)
                protected String description;
                @XmlElement(name = "Code", required = true)
                protected String code;

                /**
                 * Gets the value of the item property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link ApplicationAdvice.Details.Detail.Error.Item }
                 *     
                 */
                public ApplicationAdvice.Details.Detail.Error.Item getItem() {
                    return item;
                }

                /**
                 * Sets the value of the item property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link ApplicationAdvice.Details.Detail.Error.Item }
                 *     
                 */
                public void setItem(ApplicationAdvice.Details.Detail.Error.Item value) {
                    this.item = value;
                }

                /**
                 * Gets the value of the description property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDescription() {
                    return description;
                }

                /**
                 * Sets the value of the description property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDescription(String value) {
                    this.description = value;
                }

                /**
                 * Gets the value of the code property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCode() {
                    return code;
                }

                /**
                 * Sets the value of the code property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCode(String value) {
                    this.code = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="SKU" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="PurchaseOrderNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="UPCCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "sku",
                    "purchaseOrderNumber",
                    "upcCode"
                })
                public static class Item {

                    @XmlElement(name = "SKU", required = true)
                    protected String sku;
                    @XmlElement(name = "PurchaseOrderNumber", required = true)
                    protected String purchaseOrderNumber;
                    @XmlElement(name = "UPCCode", required = true)
                    protected String upcCode;

                    /**
                     * Gets the value of the sku property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getSKU() {
                        return sku;
                    }

                    /**
                     * Sets the value of the sku property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setSKU(String value) {
                        this.sku = value;
                    }

                    /**
                     * Gets the value of the purchaseOrderNumber property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getPurchaseOrderNumber() {
                        return purchaseOrderNumber;
                    }

                    /**
                     * Sets the value of the purchaseOrderNumber property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setPurchaseOrderNumber(String value) {
                        this.purchaseOrderNumber = value;
                    }

                    /**
                     * Gets the value of the upcCode property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getUPCCode() {
                        return upcCode;
                    }

                    /**
                     * Sets the value of the upcCode property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setUPCCode(String value) {
                        this.upcCode = value;
                    }

                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ApplicationAdviceHeader">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ReferenceDate" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="ReferenceNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="TransactionType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="VendorNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "applicationAdviceHeader"
    })
    public static class Header {

        @XmlElement(name = "ApplicationAdviceHeader", required = true)
        protected ApplicationAdvice.Header.ApplicationAdviceHeader applicationAdviceHeader;

        /**
         * Gets the value of the applicationAdviceHeader property.
         * 
         * @return
         *     possible object is
         *     {@link ApplicationAdvice.Header.ApplicationAdviceHeader }
         *     
         */
        public ApplicationAdvice.Header.ApplicationAdviceHeader getApplicationAdviceHeader() {
            return applicationAdviceHeader;
        }

        /**
         * Sets the value of the applicationAdviceHeader property.
         * 
         * @param value
         *     allowed object is
         *     {@link ApplicationAdvice.Header.ApplicationAdviceHeader }
         *     
         */
        public void setApplicationAdviceHeader(ApplicationAdvice.Header.ApplicationAdviceHeader value) {
            this.applicationAdviceHeader = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ReferenceDate" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="ReferenceNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="TransactionType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="VendorNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "referenceDate",
            "referenceNumber",
            "transactionType",
            "vendorNumber"
        })
        public static class ApplicationAdviceHeader {

            @XmlElement(name = "ReferenceDate")
            protected int referenceDate;
            @XmlElement(name = "ReferenceNumber", required = true)
            protected String referenceNumber;
            @XmlElement(name = "TransactionType", required = true)
            protected String transactionType;
            @XmlElement(name = "VendorNumber", required = true)
            protected String vendorNumber;

            /**
             * Gets the value of the referenceDate property.
             * 
             */
            public int getReferenceDate() {
                return referenceDate;
            }

            /**
             * Sets the value of the referenceDate property.
             * 
             */
            public void setReferenceDate(int value) {
                this.referenceDate = value;
            }

            /**
             * Gets the value of the referenceNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getReferenceNumber() {
                return referenceNumber;
            }

            /**
             * Sets the value of the referenceNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setReferenceNumber(String value) {
                this.referenceNumber = value;
            }

            /**
             * Gets the value of the transactionType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTransactionType() {
                return transactionType;
            }

            /**
             * Sets the value of the transactionType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTransactionType(String value) {
                this.transactionType = value;
            }

            /**
             * Gets the value of the vendorNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVendorNumber() {
                return vendorNumber;
            }

            /**
             * Sets the value of the vendorNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVendorNumber(String value) {
                this.vendorNumber = value;
            }

        }

    }

}
