//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.04 at 04:00:18 PM EDT 
//


package com.staples.jaxb.beans;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.staples.jaxb.beans package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.staples.jaxb.beans
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Invoice }
     * 
     */
    public Invoice createInvoice() {
        return new Invoice();
    }

    /**
     * Create an instance of {@link Invoice.Details }
     * 
     */
    public Invoice.Details createInvoiceDetails() {
        return new Invoice.Details();
    }

    /**
     * Create an instance of {@link Invoice.Details.Detail }
     * 
     */
    public Invoice.Details.Detail createInvoiceDetailsDetail() {
        return new Invoice.Details.Detail();
    }

    /**
     * Create an instance of {@link Invoice.Details.Detail.PriceList }
     * 
     */
    public Invoice.Details.Detail.PriceList createInvoiceDetailsDetailPriceList() {
        return new Invoice.Details.Detail.PriceList();
    }

    /**
     * Create an instance of {@link Invoice.Details.Detail.PriceList.Unit }
     * 
     */
    public Invoice.Details.Detail.PriceList.Unit createInvoiceDetailsDetailPriceListUnit() {
        return new Invoice.Details.Detail.PriceList.Unit();
    }

    /**
     * Create an instance of {@link Invoice.Details.Detail.PriceList.Unit.Amount }
     * 
     */
    public Invoice.Details.Detail.PriceList.Unit.Amount createInvoiceDetailsDetailPriceListUnitAmount() {
        return new Invoice.Details.Detail.PriceList.Unit.Amount();
    }

    /**
     * Create an instance of {@link Invoice.Details.Detail.PriceList.List }
     * 
     */
    public Invoice.Details.Detail.PriceList.List createInvoiceDetailsDetailPriceListList() {
        return new Invoice.Details.Detail.PriceList.List();
    }

    /**
     * Create an instance of {@link Invoice.Details.Detail.PriceList.List.Amount }
     * 
     */
    public Invoice.Details.Detail.PriceList.List.Amount createInvoiceDetailsDetailPriceListListAmount() {
        return new Invoice.Details.Detail.PriceList.List.Amount();
    }

    /**
     * Create an instance of {@link Invoice.Details.Detail.DateList }
     * 
     */
    public Invoice.Details.Detail.DateList createInvoiceDetailsDetailDateList() {
        return new Invoice.Details.Detail.DateList();
    }

    /**
     * Create an instance of {@link Invoice.Details.Detail.QuantityList }
     * 
     */
    public Invoice.Details.Detail.QuantityList createInvoiceDetailsDetailQuantityList() {
        return new Invoice.Details.Detail.QuantityList();
    }

    /**
     * Create an instance of {@link Invoice.Details.Detail.DiscountList }
     * 
     */
    public Invoice.Details.Detail.DiscountList createInvoiceDetailsDetailDiscountList() {
        return new Invoice.Details.Detail.DiscountList();
    }

    /**
     * Create an instance of {@link Invoice.Details.Detail.DiscountList.Discount }
     * 
     */
    public Invoice.Details.Detail.DiscountList.Discount createInvoiceDetailsDetailDiscountListDiscount() {
        return new Invoice.Details.Detail.DiscountList.Discount();
    }

    /**
     * Create an instance of {@link Invoice.Details.Detail.CodeList }
     * 
     */
    public Invoice.Details.Detail.CodeList createInvoiceDetailsDetailCodeList() {
        return new Invoice.Details.Detail.CodeList();
    }

    /**
     * Create an instance of {@link Invoice.Details.Detail.CodeList.PaymentTerm }
     * 
     */
    public Invoice.Details.Detail.CodeList.PaymentTerm createInvoiceDetailsDetailCodeListPaymentTerm() {
        return new Invoice.Details.Detail.CodeList.PaymentTerm();
    }

    /**
     * Create an instance of {@link Invoice.Details.Detail.CodeList.PaymentTerm.AmountList }
     * 
     */
    public Invoice.Details.Detail.CodeList.PaymentTerm.AmountList createInvoiceDetailsDetailCodeListPaymentTermAmountList() {
        return new Invoice.Details.Detail.CodeList.PaymentTerm.AmountList();
    }

    /**
     * Create an instance of {@link Invoice.Details.Detail.CodeList.PaymentTerm.AmountList.Discount }
     * 
     */
    public Invoice.Details.Detail.CodeList.PaymentTerm.AmountList.Discount createInvoiceDetailsDetailCodeListPaymentTermAmountListDiscount() {
        return new Invoice.Details.Detail.CodeList.PaymentTerm.AmountList.Discount();
    }

    /**
     * Create an instance of {@link Invoice.Details.Detail.CodeList.PaymentTerm.DateList }
     * 
     */
    public Invoice.Details.Detail.CodeList.PaymentTerm.DateList createInvoiceDetailsDetailCodeListPaymentTermDateList() {
        return new Invoice.Details.Detail.CodeList.PaymentTerm.DateList();
    }

    /**
     * Create an instance of {@link Invoice.Details.Detail.PackageTrackingList }
     * 
     */
    public Invoice.Details.Detail.PackageTrackingList createInvoiceDetailsDetailPackageTrackingList() {
        return new Invoice.Details.Detail.PackageTrackingList();
    }

    /**
     * Create an instance of {@link Invoice.Details.Detail.ChargeList }
     * 
     */
    public Invoice.Details.Detail.ChargeList createInvoiceDetailsDetailChargeList() {
        return new Invoice.Details.Detail.ChargeList();
    }

    /**
     * Create an instance of {@link Invoice.Details.Detail.ChargeList.Charge }
     * 
     */
    public Invoice.Details.Detail.ChargeList.Charge createInvoiceDetailsDetailChargeListCharge() {
        return new Invoice.Details.Detail.ChargeList.Charge();
    }

    /**
     * Create an instance of {@link Invoice.Details.Detail.ChargeList.Charge.Amount }
     * 
     */
    public Invoice.Details.Detail.ChargeList.Charge.Amount createInvoiceDetailsDetailChargeListChargeAmount() {
        return new Invoice.Details.Detail.ChargeList.Charge.Amount();
    }

    /**
     * Create an instance of {@link Invoice.Details.Detail.ItemList }
     * 
     */
    public Invoice.Details.Detail.ItemList createInvoiceDetailsDetailItemList() {
        return new Invoice.Details.Detail.ItemList();
    }

    /**
     * Create an instance of {@link Invoice.Details.Detail.ItemList.Invoice2 }
     * 
     */
    public Invoice.Details.Detail.ItemList.Invoice2 createInvoiceDetailsDetailItemListInvoice2() {
        return new Invoice.Details.Detail.ItemList.Invoice2();
    }

    /**
     * Create an instance of {@link Invoice.Header }
     * 
     */
    public Invoice.Header createInvoiceHeader() {
        return new Invoice.Header();
    }

    /**
     * Create an instance of {@link Invoice.Header.InvoiceHeader }
     * 
     */
    public Invoice.Header.InvoiceHeader createInvoiceHeaderInvoiceHeader() {
        return new Invoice.Header.InvoiceHeader();
    }

    /**
     * Create an instance of {@link Invoice.Header.InvoiceHeader.DateList }
     * 
     */
    public Invoice.Header.InvoiceHeader.DateList createInvoiceHeaderInvoiceHeaderDateList() {
        return new Invoice.Header.InvoiceHeader.DateList();
    }

    /**
     * Create an instance of {@link Invoice.Header.InvoiceHeader.CodeList }
     * 
     */
    public Invoice.Header.InvoiceHeader.CodeList createInvoiceHeaderInvoiceHeaderCodeList() {
        return new Invoice.Header.InvoiceHeader.CodeList();
    }

    /**
     * Create an instance of {@link Invoice.Header.InvoiceHeader.DiscountList }
     * 
     */
    public Invoice.Header.InvoiceHeader.DiscountList createInvoiceHeaderInvoiceHeaderDiscountList() {
        return new Invoice.Header.InvoiceHeader.DiscountList();
    }

    /**
     * Create an instance of {@link Invoice.Header.InvoiceHeader.DiscountList.Discount }
     * 
     */
    public Invoice.Header.InvoiceHeader.DiscountList.Discount createInvoiceHeaderInvoiceHeaderDiscountListDiscount() {
        return new Invoice.Header.InvoiceHeader.DiscountList.Discount();
    }

    /**
     * Create an instance of {@link Invoice.Header.InvoiceHeader.LocationList }
     * 
     */
    public Invoice.Header.InvoiceHeader.LocationList createInvoiceHeaderInvoiceHeaderLocationList() {
        return new Invoice.Header.InvoiceHeader.LocationList();
    }

    /**
     * Create an instance of {@link Invoice.Header.InvoiceHeader.OrganizationalList }
     * 
     */
    public Invoice.Header.InvoiceHeader.OrganizationalList createInvoiceHeaderInvoiceHeaderOrganizationalList() {
        return new Invoice.Header.InvoiceHeader.OrganizationalList();
    }

    /**
     * Create an instance of {@link Invoice.Header.InvoiceHeader.OrganizationList }
     * 
     */
    public Invoice.Header.InvoiceHeader.OrganizationList createInvoiceHeaderInvoiceHeaderOrganizationList() {
        return new Invoice.Header.InvoiceHeader.OrganizationList();
    }

    /**
     * Create an instance of {@link Invoice.Header.InvoiceHeader.AmountList }
     * 
     */
    public Invoice.Header.InvoiceHeader.AmountList createInvoiceHeaderInvoiceHeaderAmountList() {
        return new Invoice.Header.InvoiceHeader.AmountList();
    }

    /**
     * Create an instance of {@link Invoice.Header.InvoiceHeader.AmountList.SubjectToDiscount }
     * 
     */
    public Invoice.Header.InvoiceHeader.AmountList.SubjectToDiscount createInvoiceHeaderInvoiceHeaderAmountListSubjectToDiscount() {
        return new Invoice.Header.InvoiceHeader.AmountList.SubjectToDiscount();
    }

    /**
     * Create an instance of {@link Invoice.Header.InvoiceHeader.AmountList.DiscountedDue }
     * 
     */
    public Invoice.Header.InvoiceHeader.AmountList.DiscountedDue createInvoiceHeaderInvoiceHeaderAmountListDiscountedDue() {
        return new Invoice.Header.InvoiceHeader.AmountList.DiscountedDue();
    }

    /**
     * Create an instance of {@link Invoice.Header.InvoiceHeader.AmountList.DiscountTerms }
     * 
     */
    public Invoice.Header.InvoiceHeader.AmountList.DiscountTerms createInvoiceHeaderInvoiceHeaderAmountListDiscountTerms() {
        return new Invoice.Header.InvoiceHeader.AmountList.DiscountTerms();
    }

    /**
     * Create an instance of {@link Invoice.Header.InvoiceHeader.ChargeList }
     * 
     */
    public Invoice.Header.InvoiceHeader.ChargeList createInvoiceHeaderInvoiceHeaderChargeList() {
        return new Invoice.Header.InvoiceHeader.ChargeList();
    }

    /**
     * Create an instance of {@link Invoice.Header.InvoiceHeader.ChargeList.Additional }
     * 
     */
    public Invoice.Header.InvoiceHeader.ChargeList.Additional createInvoiceHeaderInvoiceHeaderChargeListAdditional() {
        return new Invoice.Header.InvoiceHeader.ChargeList.Additional();
    }

    /**
     * Create an instance of {@link Invoice.Header.InvoiceHeader.TotalList }
     * 
     */
    public Invoice.Header.InvoiceHeader.TotalList createInvoiceHeaderInvoiceHeaderTotalList() {
        return new Invoice.Header.InvoiceHeader.TotalList();
    }

    /**
     * Create an instance of {@link Invoice.Header.InvoiceHeader.TotalList.AmountList }
     * 
     */
    public Invoice.Header.InvoiceHeader.TotalList.AmountList createInvoiceHeaderInvoiceHeaderTotalListAmountList() {
        return new Invoice.Header.InvoiceHeader.TotalList.AmountList();
    }

    /**
     * Create an instance of {@link Invoice.Header.InvoiceHeader.TotalList.AmountList.Invoice1 }
     * 
     */
    public Invoice.Header.InvoiceHeader.TotalList.AmountList.Invoice1 createInvoiceHeaderInvoiceHeaderTotalListAmountListInvoice1() {
        return new Invoice.Header.InvoiceHeader.TotalList.AmountList.Invoice1();
    }

    /**
     * Create an instance of {@link Invoice.Header.InvoiceHeader.PartyList }
     * 
     */
    public Invoice.Header.InvoiceHeader.PartyList createInvoiceHeaderInvoiceHeaderPartyList() {
        return new Invoice.Header.InvoiceHeader.PartyList();
    }

    /**
     * Create an instance of {@link Invoice.Header.InvoiceHeader.PartyList.BillTo }
     * 
     */
    public Invoice.Header.InvoiceHeader.PartyList.BillTo createInvoiceHeaderInvoiceHeaderPartyListBillTo() {
        return new Invoice.Header.InvoiceHeader.PartyList.BillTo();
    }

    /**
     * Create an instance of {@link Invoice.Header.InvoiceHeader.PartyList.BillTo.NameList }
     * 
     */
    public Invoice.Header.InvoiceHeader.PartyList.BillTo.NameList createInvoiceHeaderInvoiceHeaderPartyListBillToNameList() {
        return new Invoice.Header.InvoiceHeader.PartyList.BillTo.NameList();
    }

    /**
     * Create an instance of {@link Invoice.Header.InvoiceHeader.PartyList.ShipTo }
     * 
     */
    public Invoice.Header.InvoiceHeader.PartyList.ShipTo createInvoiceHeaderInvoiceHeaderPartyListShipTo() {
        return new Invoice.Header.InvoiceHeader.PartyList.ShipTo();
    }

    /**
     * Create an instance of {@link Invoice.Header.InvoiceHeader.PartyList.ShipTo.Location }
     * 
     */
    public Invoice.Header.InvoiceHeader.PartyList.ShipTo.Location createInvoiceHeaderInvoiceHeaderPartyListShipToLocation() {
        return new Invoice.Header.InvoiceHeader.PartyList.ShipTo.Location();
    }

    /**
     * Create an instance of {@link Invoice.Header.InvoiceHeader.PartyList.ShipTo.Location.Address }
     * 
     */
    public Invoice.Header.InvoiceHeader.PartyList.ShipTo.Location.Address createInvoiceHeaderInvoiceHeaderPartyListShipToLocationAddress() {
        return new Invoice.Header.InvoiceHeader.PartyList.ShipTo.Location.Address();
    }

    /**
     * Create an instance of {@link Invoice.Header.InvoiceHeader.PartyList.ShipTo.NameList }
     * 
     */
    public Invoice.Header.InvoiceHeader.PartyList.ShipTo.NameList createInvoiceHeaderInvoiceHeaderPartyListShipToNameList() {
        return new Invoice.Header.InvoiceHeader.PartyList.ShipTo.NameList();
    }

    /**
     * Create an instance of {@link Invoice.Header.InvoiceHeader.PaymentTerms }
     * 
     */
    public Invoice.Header.InvoiceHeader.PaymentTerms createInvoiceHeaderInvoiceHeaderPaymentTerms() {
        return new Invoice.Header.InvoiceHeader.PaymentTerms();
    }

    /**
     * Create an instance of {@link Invoice.Header.InvoiceHeader.PaymentTerms.DateList }
     * 
     */
    public Invoice.Header.InvoiceHeader.PaymentTerms.DateList createInvoiceHeaderInvoiceHeaderPaymentTermsDateList() {
        return new Invoice.Header.InvoiceHeader.PaymentTerms.DateList();
    }

    /**
     * Create an instance of {@link Invoice.Header.InvoiceHeader.PurchaseOrderList }
     * 
     */
    public Invoice.Header.InvoiceHeader.PurchaseOrderList createInvoiceHeaderInvoiceHeaderPurchaseOrderList() {
        return new Invoice.Header.InvoiceHeader.PurchaseOrderList();
    }

    /**
     * Create an instance of {@link Invoice.Details.Detail.ReturnPurchaseOrder }
     * 
     */
    public Invoice.Details.Detail.ReturnPurchaseOrder createInvoiceDetailsDetailReturnPurchaseOrder() {
        return new Invoice.Details.Detail.ReturnPurchaseOrder();
    }

    /**
     * Create an instance of {@link Invoice.Details.Detail.VendorItem }
     * 
     */
    public Invoice.Details.Detail.VendorItem createInvoiceDetailsDetailVendorItem() {
        return new Invoice.Details.Detail.VendorItem();
    }

    /**
     * Create an instance of {@link Invoice.Details.Detail.Shipment }
     * 
     */
    public Invoice.Details.Detail.Shipment createInvoiceDetailsDetailShipment() {
        return new Invoice.Details.Detail.Shipment();
    }

    /**
     * Create an instance of {@link Invoice.Details.Detail.OriginalInvoice }
     * 
     */
    public Invoice.Details.Detail.OriginalInvoice createInvoiceDetailsDetailOriginalInvoice() {
        return new Invoice.Details.Detail.OriginalInvoice();
    }

    /**
     * Create an instance of {@link Invoice.Details.Detail.ReturnAuthorization }
     * 
     */
    public Invoice.Details.Detail.ReturnAuthorization createInvoiceDetailsDetailReturnAuthorization() {
        return new Invoice.Details.Detail.ReturnAuthorization();
    }

    /**
     * Create an instance of {@link Invoice.Details.Detail.PriceList.Unit.Amount.Currency }
     * 
     */
    public Invoice.Details.Detail.PriceList.Unit.Amount.Currency createInvoiceDetailsDetailPriceListUnitAmountCurrency() {
        return new Invoice.Details.Detail.PriceList.Unit.Amount.Currency();
    }

    /**
     * Create an instance of {@link Invoice.Details.Detail.PriceList.List.Amount.Currency }
     * 
     */
    public Invoice.Details.Detail.PriceList.List.Amount.Currency createInvoiceDetailsDetailPriceListListAmountCurrency() {
        return new Invoice.Details.Detail.PriceList.List.Amount.Currency();
    }

    /**
     * Create an instance of {@link Invoice.Details.Detail.DateList.NetInvoiceDue }
     * 
     */
    public Invoice.Details.Detail.DateList.NetInvoiceDue createInvoiceDetailsDetailDateListNetInvoiceDue() {
        return new Invoice.Details.Detail.DateList.NetInvoiceDue();
    }

    /**
     * Create an instance of {@link Invoice.Details.Detail.QuantityList.Invoice3 }
     * 
     */
    public Invoice.Details.Detail.QuantityList.Invoice3 createInvoiceDetailsDetailQuantityListInvoice3() {
        return new Invoice.Details.Detail.QuantityList.Invoice3();
    }

    /**
     * Create an instance of {@link Invoice.Details.Detail.QuantityList.Cancelled }
     * 
     */
    public Invoice.Details.Detail.QuantityList.Cancelled createInvoiceDetailsDetailQuantityListCancelled() {
        return new Invoice.Details.Detail.QuantityList.Cancelled();
    }

    /**
     * Create an instance of {@link Invoice.Details.Detail.DiscountList.Discount.Date }
     * 
     */
    public Invoice.Details.Detail.DiscountList.Discount.Date createInvoiceDetailsDetailDiscountListDiscountDate() {
        return new Invoice.Details.Detail.DiscountList.Discount.Date();
    }

    /**
     * Create an instance of {@link Invoice.Details.Detail.CodeList.Credit }
     * 
     */
    public Invoice.Details.Detail.CodeList.Credit createInvoiceDetailsDetailCodeListCredit() {
        return new Invoice.Details.Detail.CodeList.Credit();
    }

    /**
     * Create an instance of {@link Invoice.Details.Detail.CodeList.PaymentTerm.AmountList.Discount.Currency }
     * 
     */
    public Invoice.Details.Detail.CodeList.PaymentTerm.AmountList.Discount.Currency createInvoiceDetailsDetailCodeListPaymentTermAmountListDiscountCurrency() {
        return new Invoice.Details.Detail.CodeList.PaymentTerm.AmountList.Discount.Currency();
    }

    /**
     * Create an instance of {@link Invoice.Details.Detail.CodeList.PaymentTerm.DateList.Basis }
     * 
     */
    public Invoice.Details.Detail.CodeList.PaymentTerm.DateList.Basis createInvoiceDetailsDetailCodeListPaymentTermDateListBasis() {
        return new Invoice.Details.Detail.CodeList.PaymentTerm.DateList.Basis();
    }

    /**
     * Create an instance of {@link Invoice.Details.Detail.PackageTrackingList.PackageTracking }
     * 
     */
    public Invoice.Details.Detail.PackageTrackingList.PackageTracking createInvoiceDetailsDetailPackageTrackingListPackageTracking() {
        return new Invoice.Details.Detail.PackageTrackingList.PackageTracking();
    }

    /**
     * Create an instance of {@link Invoice.Details.Detail.ChargeList.Charge.Amount.Currency }
     * 
     */
    public Invoice.Details.Detail.ChargeList.Charge.Amount.Currency createInvoiceDetailsDetailChargeListChargeAmountCurrency() {
        return new Invoice.Details.Detail.ChargeList.Charge.Amount.Currency();
    }

    /**
     * Create an instance of {@link Invoice.Details.Detail.ItemList.Invoice2 .SerialNumberList }
     * 
     */
    public Invoice.Details.Detail.ItemList.Invoice2 .SerialNumberList createInvoiceDetailsDetailItemListInvoice2SerialNumberList() {
        return new Invoice.Details.Detail.ItemList.Invoice2 .SerialNumberList();
    }

    /**
     * Create an instance of {@link Invoice.Header.InvoiceHeader.Carrier }
     * 
     */
    public Invoice.Header.InvoiceHeader.Carrier createInvoiceHeaderInvoiceHeaderCarrier() {
        return new Invoice.Header.InvoiceHeader.Carrier();
    }

    /**
     * Create an instance of {@link Invoice.Header.InvoiceHeader.BillOfLading }
     * 
     */
    public Invoice.Header.InvoiceHeader.BillOfLading createInvoiceHeaderInvoiceHeaderBillOfLading() {
        return new Invoice.Header.InvoiceHeader.BillOfLading();
    }

    /**
     * Create an instance of {@link Invoice.Header.InvoiceHeader.Vendor }
     * 
     */
    public Invoice.Header.InvoiceHeader.Vendor createInvoiceHeaderInvoiceHeaderVendor() {
        return new Invoice.Header.InvoiceHeader.Vendor();
    }

    /**
     * Create an instance of {@link Invoice.Header.InvoiceHeader.DateList.Ship }
     * 
     */
    public Invoice.Header.InvoiceHeader.DateList.Ship createInvoiceHeaderInvoiceHeaderDateListShip() {
        return new Invoice.Header.InvoiceHeader.DateList.Ship();
    }

    /**
     * Create an instance of {@link Invoice.Header.InvoiceHeader.CodeList.ShipmentPaymentMethod }
     * 
     */
    public Invoice.Header.InvoiceHeader.CodeList.ShipmentPaymentMethod createInvoiceHeaderInvoiceHeaderCodeListShipmentPaymentMethod() {
        return new Invoice.Header.InvoiceHeader.CodeList.ShipmentPaymentMethod();
    }

    /**
     * Create an instance of {@link Invoice.Header.InvoiceHeader.CodeList.DocumentType }
     * 
     */
    public Invoice.Header.InvoiceHeader.CodeList.DocumentType createInvoiceHeaderInvoiceHeaderCodeListDocumentType() {
        return new Invoice.Header.InvoiceHeader.CodeList.DocumentType();
    }

    /**
     * Create an instance of {@link Invoice.Header.InvoiceHeader.DiscountList.Discount.Date }
     * 
     */
    public Invoice.Header.InvoiceHeader.DiscountList.Discount.Date createInvoiceHeaderInvoiceHeaderDiscountListDiscountDate() {
        return new Invoice.Header.InvoiceHeader.DiscountList.Discount.Date();
    }

    /**
     * Create an instance of {@link Invoice.Header.InvoiceHeader.LocationList.ShipFrom }
     * 
     */
    public Invoice.Header.InvoiceHeader.LocationList.ShipFrom createInvoiceHeaderInvoiceHeaderLocationListShipFrom() {
        return new Invoice.Header.InvoiceHeader.LocationList.ShipFrom();
    }

    /**
     * Create an instance of {@link Invoice.Header.InvoiceHeader.OrganizationalList.Enterprise }
     * 
     */
    public Invoice.Header.InvoiceHeader.OrganizationalList.Enterprise createInvoiceHeaderInvoiceHeaderOrganizationalListEnterprise() {
        return new Invoice.Header.InvoiceHeader.OrganizationalList.Enterprise();
    }

    /**
     * Create an instance of {@link Invoice.Header.InvoiceHeader.OrganizationalList.BusinessUnit }
     * 
     */
    public Invoice.Header.InvoiceHeader.OrganizationalList.BusinessUnit createInvoiceHeaderInvoiceHeaderOrganizationalListBusinessUnit() {
        return new Invoice.Header.InvoiceHeader.OrganizationalList.BusinessUnit();
    }

    /**
     * Create an instance of {@link Invoice.Header.InvoiceHeader.OrganizationList.Division }
     * 
     */
    public Invoice.Header.InvoiceHeader.OrganizationList.Division createInvoiceHeaderInvoiceHeaderOrganizationListDivision() {
        return new Invoice.Header.InvoiceHeader.OrganizationList.Division();
    }

    /**
     * Create an instance of {@link Invoice.Header.InvoiceHeader.AmountList.SubjectToDiscount.Currency }
     * 
     */
    public Invoice.Header.InvoiceHeader.AmountList.SubjectToDiscount.Currency createInvoiceHeaderInvoiceHeaderAmountListSubjectToDiscountCurrency() {
        return new Invoice.Header.InvoiceHeader.AmountList.SubjectToDiscount.Currency();
    }

    /**
     * Create an instance of {@link Invoice.Header.InvoiceHeader.AmountList.DiscountedDue.Currency }
     * 
     */
    public Invoice.Header.InvoiceHeader.AmountList.DiscountedDue.Currency createInvoiceHeaderInvoiceHeaderAmountListDiscountedDueCurrency() {
        return new Invoice.Header.InvoiceHeader.AmountList.DiscountedDue.Currency();
    }

    /**
     * Create an instance of {@link Invoice.Header.InvoiceHeader.AmountList.DiscountTerms.Currency }
     * 
     */
    public Invoice.Header.InvoiceHeader.AmountList.DiscountTerms.Currency createInvoiceHeaderInvoiceHeaderAmountListDiscountTermsCurrency() {
        return new Invoice.Header.InvoiceHeader.AmountList.DiscountTerms.Currency();
    }

    /**
     * Create an instance of {@link Invoice.Header.InvoiceHeader.ChargeList.Additional.Charge }
     * 
     */
    public Invoice.Header.InvoiceHeader.ChargeList.Additional.Charge createInvoiceHeaderInvoiceHeaderChargeListAdditionalCharge() {
        return new Invoice.Header.InvoiceHeader.ChargeList.Additional.Charge();
    }

    /**
     * Create an instance of {@link Invoice.Header.InvoiceHeader.TotalList.DimensionList }
     * 
     */
    public Invoice.Header.InvoiceHeader.TotalList.DimensionList createInvoiceHeaderInvoiceHeaderTotalListDimensionList() {
        return new Invoice.Header.InvoiceHeader.TotalList.DimensionList();
    }

    /**
     * Create an instance of {@link Invoice.Header.InvoiceHeader.TotalList.AmountList.Invoice1 .Currency }
     * 
     */
    public Invoice.Header.InvoiceHeader.TotalList.AmountList.Invoice1 .Currency createInvoiceHeaderInvoiceHeaderTotalListAmountListInvoice1Currency() {
        return new Invoice.Header.InvoiceHeader.TotalList.AmountList.Invoice1 .Currency();
    }

    /**
     * Create an instance of {@link Invoice.Header.InvoiceHeader.PartyList.BillTo.NameList.Name }
     * 
     */
    public Invoice.Header.InvoiceHeader.PartyList.BillTo.NameList.Name createInvoiceHeaderInvoiceHeaderPartyListBillToNameListName() {
        return new Invoice.Header.InvoiceHeader.PartyList.BillTo.NameList.Name();
    }

    /**
     * Create an instance of {@link Invoice.Header.InvoiceHeader.PartyList.ShipTo.Location.Address.State }
     * 
     */
    public Invoice.Header.InvoiceHeader.PartyList.ShipTo.Location.Address.State createInvoiceHeaderInvoiceHeaderPartyListShipToLocationAddressState() {
        return new Invoice.Header.InvoiceHeader.PartyList.ShipTo.Location.Address.State();
    }

    /**
     * Create an instance of {@link Invoice.Header.InvoiceHeader.PartyList.ShipTo.NameList.Name }
     * 
     */
    public Invoice.Header.InvoiceHeader.PartyList.ShipTo.NameList.Name createInvoiceHeaderInvoiceHeaderPartyListShipToNameListName() {
        return new Invoice.Header.InvoiceHeader.PartyList.ShipTo.NameList.Name();
    }

    /**
     * Create an instance of {@link Invoice.Header.InvoiceHeader.PaymentTerms.ThresholdList }
     * 
     */
    public Invoice.Header.InvoiceHeader.PaymentTerms.ThresholdList createInvoiceHeaderInvoiceHeaderPaymentTermsThresholdList() {
        return new Invoice.Header.InvoiceHeader.PaymentTerms.ThresholdList();
    }

    /**
     * Create an instance of {@link Invoice.Header.InvoiceHeader.PaymentTerms.DateList.Basis }
     * 
     */
    public Invoice.Header.InvoiceHeader.PaymentTerms.DateList.Basis createInvoiceHeaderInvoiceHeaderPaymentTermsDateListBasis() {
        return new Invoice.Header.InvoiceHeader.PaymentTerms.DateList.Basis();
    }

    /**
     * Create an instance of {@link Invoice.Header.InvoiceHeader.PurchaseOrderList.PurchaseOrder }
     * 
     */
    public Invoice.Header.InvoiceHeader.PurchaseOrderList.PurchaseOrder createInvoiceHeaderInvoiceHeaderPurchaseOrderListPurchaseOrder() {
        return new Invoice.Header.InvoiceHeader.PurchaseOrderList.PurchaseOrder();
    }

    /**
     * Create an instance of {@link Invoice.Header.InvoiceHeader.PurchaseOrderList.OriginalPurchaseOrder }
     * 
     */
    public Invoice.Header.InvoiceHeader.PurchaseOrderList.OriginalPurchaseOrder createInvoiceHeaderInvoiceHeaderPurchaseOrderListOriginalPurchaseOrder() {
        return new Invoice.Header.InvoiceHeader.PurchaseOrderList.OriginalPurchaseOrder();
    }

}
